### ISSUE TITLE
[DOC] - Add setup instructions

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/gimme-colours#6]
# Incorrect Documentation

## Describe the error

The CONTRIBUTING.md file currently lacks specific setup instructions.

## Expected information

We need to add the following information to the `Setting Up Your Code` section:
- Installing dependencies (`npm ci`)
- Building files (`npm run build`)
- Running linter (`npm run lint`)
- Validating tests (`npm run test`)
- Generating `npm` test package (`npm pack`)
- Installing test package (`npm i -g <tgz file>`)

**Comment by shubhamayush12** [comment]
Sir I have updated and created the pull request

**Comment by shubhamayush12** [comment]
But Sir it is showing This branch has no conflict with the base branch

**Comment by shubhamayush12** [comment]
Looks like I have made a mistake

**Comment by nhcarrigan** [comment]
Hey there,

I do not see an active pull request on this project.
